//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CainzOrder
    {
        public CainzOrder()
        {
            this.CainzOrderDetail = new HashSet<CainzOrderDetail>();
        }
    
        public System.Guid OrderID { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.Guid> FactoryID { get; set; }
        public string FactoryName { get; set; }
        public string Phone { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
        public string Receiver { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public decimal Money { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.Guid> CreatorID { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> LastUpdate { get; set; }
        public string Buyer { get; set; }
        public string Remark { get; set; }
        public Nullable<int> isDraft { get; set; }
        public int IsDelete { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.Guid CainzFactoryFactoryID { get; set; }
    
        public virtual CainzFactory CainzFactory { get; set; }
        public virtual ICollection<CainzOrderDetail> CainzOrderDetail { get; set; }
    }
}
