
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace entity
{

using System;
    using System.Collections.Generic;
    
public partial class CainzTrader
{

    public CainzTrader()
    {

        this.CainzFactory = new HashSet<CainzFactory>();

        this.CainzProduct = new HashSet<CainzProduct>();

    }


    public System.Guid TraderID { get; set; }

    public string TraderName { get; set; }

    public string TraderShortName { get; set; }

    public int IsDelete { get; set; }

    public System.DateTime CreateTime { get; set; }

    public string Remark { get; set; }



    public virtual ICollection<CainzFactory> CainzFactory { get; set; }

    public virtual ICollection<CainzProduct> CainzProduct { get; set; }

}

}
