//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CainzOrderDetail
    {
        public int ID { get; set; }
        public string SnNum { get; set; }
        public int OrderNum { get; set; }
        public string NitORI { get; set; }
        public string ProductCD { get; set; }
        public string ProductName { get; set; }
        public string CdFileName { get; set; }
        public string PopDesignNo { get; set; }
        public string PopSize { get; set; }
        public string PaperKind { get; set; }
        public string PopCate { get; set; }
        public string PopCateName { get; set; }
        public string Colour { get; set; }
        public Nullable<int> POPNum { get; set; }
        public Nullable<int> RealNum { get; set; }
        public int UnitNum { get; set; }
        public string UnitName { get; set; }
        public Nullable<System.DateTime> ExpectDate { get; set; }
        public decimal Price { get; set; }
        public System.DateTime ProbabilityDate { get; set; }
        public string ETD { get; set; }
        public string Reference { get; set; }
        public decimal PrintMoney { get; set; }
        public decimal CheckMoney { get; set; }
        public decimal InvoiceMoney { get; set; }
        public string Sample { get; set; }
        public int Status { get; set; }
        public int IsDelete { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string Remark { get; set; }
        public string BatchNum { get; set; }
        public Nullable<int> RowNo { get; set; }
    }
}
