//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CainzFactory
    {
        public CainzFactory()
        {
            this.CainzOrder = new HashSet<CainzOrder>();
        }
    
        public System.Guid FactoryID { get; set; }
        public string FactoryName { get; set; }
        public string FactoryNameJP { get; set; }
        public string FactoryAddress { get; set; }
        public Nullable<System.Guid> TraderID { get; set; }
        public string TraderName { get; set; }
        public string Contact { get; set; }
        public string ContactPhone { get; set; }
        public string Receiver { get; set; }
        public string ReceiverPhone { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int Deleted { get; set; }
        public System.Guid CainzTraderTraderID { get; set; }
    
        public virtual ICollection<CainzOrder> CainzOrder { get; set; }
        public virtual CainzTrader CainzTrader { get; set; }
    }
}
