
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace entity
{

using System;
    using System.Collections.Generic;
    
public partial class CainzOrderDetail
{

    public System.Guid OrderDetailID { get; set; }

    public System.Guid OrderID { get; set; }

    public Nullable<int> RowNo { get; set; }

    public System.Guid ProductID { get; set; }

    public string ProductBarcode { get; set; }

    public string ProductName { get; set; }

    public string ProductMaterial { get; set; }

    public string ProductSize { get; set; }

    public string ProductColor { get; set; }

    public Nullable<decimal> ProductPrice { get; set; }

    public Nullable<int> POPNum { get; set; }

    public Nullable<System.Guid> UnitID { get; set; }

    public string UnitName { get; set; }

    public Nullable<System.DateTime> ExpectDate { get; set; }

    public string ExpectDateFormat { get; set; }

    public decimal TotalMoney { get; set; }

    public string Sample { get; set; }

    public int Status { get; set; }

    public int IsDelete { get; set; }

    public System.DateTime CreateTime { get; set; }

    public string Remark { get; set; }

    public string BatchNo { get; set; }

    public System.Guid CainzOrderOrderID { get; set; }

    public System.Guid CainzProductProductID { get; set; }



    public virtual CainzOrder CainzOrder { get; set; }

    public virtual CainzProduct CainzProduct { get; set; }

}

}
