//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckStorageDetail
    {
        public int ID { get; set; }
        public string CheckNum { get; set; }
        public string LocaNum { get; set; }
        public string LocaName { get; set; }
        public string LocaBarCode { get; set; }
        public string RealProductName { get; set; }
        public string RealBarCode { get; set; }
        public int RealNum { get; set; }
        public string SouProcutName { get; set; }
        public string SouBarCode { get; set; }
        public int SouNum { get; set; }
    }
}
