//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConstructionDetail
    {
        public int ID { get; set; }
        public string SnNum { get; set; }
        public string OrderNum { get; set; }
        public string BarCode { get; set; }
        public string ProductName { get; set; }
        public string PopSize { get; set; }
        public Nullable<int> PopNum { get; set; }
        public Nullable<int> RealNum { get; set; }
        public Nullable<int> ShenShu { get; set; }
        public Nullable<int> MinNum { get; set; }
        public string Size { get; set; }
        public string Kshu { get; set; }
        public string Color { get; set; }
        public Nullable<int> Positive { get; set; }
        public Nullable<int> Back { get; set; }
    }
}
