//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Construction
    {
        public int ID { get; set; }
        public string OrderNum { get; set; }
        public System.DateTime CompleteDate { get; set; }
        public System.DateTime SendDate { get; set; }
        public string PrintNum { get; set; }
        public System.DateTime BeginDate { get; set; }
        public string CusNum { get; set; }
        public string CusName { get; set; }
        public string Phone { get; set; }
        public string Revevier { get; set; }
        public string Address { get; set; }
        public string Remark { get; set; }
        public string HouDao { get; set; }
        public string PrintRequire { get; set; }
        public string GM { get; set; }
        public string YM { get; set; }
        public string PD { get; set; }
        public string ZD { get; set; }
        public string UV { get; set; }
        public string DB { get; set; }
        public string SG { get; set; }
        public string ZY { get; set; }
        public string YH { get; set; }
        public string GMValue { get; set; }
        public string YMValue { get; set; }
        public string PDValue { get; set; }
        public string ZDValue { get; set; }
        public string UVValue { get; set; }
        public string DBValue { get; set; }
        public string SGValue { get; set; }
        public string ZYValue { get; set; }
        public string YHValue { get; set; }
        public string TJ { get; set; }
        public string TY { get; set; }
        public string DH { get; set; }
        public string AutoSG { get; set; }
        public string ZDing { get; set; }
        public string HH { get; set; }
        public string MQ { get; set; }
        public string YX { get; set; }
        public string Other { get; set; }
        public string TJValue { get; set; }
        public string TYValue { get; set; }
        public string DHValue { get; set; }
        public string AutoSGValue { get; set; }
        public string ZDingValue { get; set; }
        public string HHValue { get; set; }
        public string MQValue { get; set; }
        public string YXValue { get; set; }
        public string OtherValue { get; set; }
        public string WordSize { get; set; }
        public Nullable<int> WordCount { get; set; }
        public Nullable<int> CTPCount { get; set; }
        public Nullable<int> PSCount { get; set; }
        public string Kaiqie { get; set; }
        public string CHouDAO { get; set; }
        public string Qingdian { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> IsPrint { get; set; }
        public System.DateTime PrintTime { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
