//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int ID { get; set; }
        public string CustomerNum { get; set; }
        public string CustomerName { get; set; }
        public string Phone { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
        public string Invoice { get; set; }
        public string Company { get; set; }
        public string SendAddress { get; set; }
        public string Receiver { get; set; }
        public string Telephone { get; set; }
        public string Fax { get; set; }
        public string FinanceContact { get; set; }
        public string BankName { get; set; }
        public string CardNum { get; set; }
        public string Taxpayer { get; set; }
        public string Remark { get; set; }
        public string FirstNum { get; set; }
        public string SecondNum { get; set; }
    }
}
