//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class InStorSingleDetail
    {
        public int ID { get; set; }
        public int InStorDetailID { get; set; }
        public string SingleNum { get; set; }
        public string InStorNum { get; set; }
        public string ProductName { get; set; }
        public string BarCode { get; set; }
        public string BatchNum { get; set; }
        public string UserName { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
