//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Material
    {
        public int ID { get; set; }
        public string ProductName { get; set; }
        public string BarCode { get; set; }
        public string ProductNum { get; set; }
        public string CdFileName { get; set; }
        public string PopDesign { get; set; }
        public string PopSize { get; set; }
        public string PagerKind { get; set; }
        public string Colour { get; set; }
        public int InitNum { get; set; }
        public int Num { get; set; }
        public int WarnNum { get; set; }
        public int Unit { get; set; }
        public string UnitName { get; set; }
        public string CategoryNum { get; set; }
        public string ProSpec { get; set; }
        public string Description { get; set; }
        public decimal InPrice { get; set; }
        public decimal Price { get; set; }
        public int IsDelete { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string DefaultLocal { get; set; }
        public int Status { get; set; }
        public string CusNum { get; set; }
        public string CusName { get; set; }
        public string Remark { get; set; }
    }
}
