//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JingChenDBEntities2 : DbContext
    {
        public JingChenDBEntities2()
            : base("name=JingChenDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CainzCustomer> CainzCustomer { get; set; }
        public virtual DbSet<CainzOrderDetail> CainzOrderDetail { get; set; }
        public virtual DbSet<CainzOrders> CainzOrders { get; set; }
        public virtual DbSet<CainzProduct> CainzProduct { get; set; }
        public virtual DbSet<CainzTrader> CainzTrader { get; set; }
        public virtual DbSet<CusCategory> CusCategory { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
    }
}
