//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JingChenDBEntities2 : DbContext
    {
        public JingChenDBEntities2()
            : base("name=JingChenDBEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CainzCustomer> CainzCustomer { get; set; }
        public DbSet<CainzOrderDetail> CainzOrderDetail { get; set; }
        public DbSet<CainzOrders> CainzOrders { get; set; }
        public DbSet<CainzProduct> CainzProduct { get; set; }
        public DbSet<CainzTrader> CainzTrader { get; set; }
        public DbSet<CusCategory> CusCategory { get; set; }
        public DbSet<Customer> Customer { get; set; }
    }
}
