//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoveStorageDetail
    {
        public int ID { get; set; }
        public string MoveNum { get; set; }
        public string ProductName { get; set; }
        public string BarCode { get; set; }
        public int Num { get; set; }
        public string FromNum { get; set; }
        public string FromName { get; set; }
        public string ToNum { get; set; }
        public string ToName { get; set; }
        public string BatchNum { get; set; }
    }
}
