//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutStorage
    {
        public int ID { get; set; }
        public string OrderNum { get; set; }
        public string CusNum { get; set; }
        public string CusName { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public string PCode { get; set; }
        public string CCode { get; set; }
        public string Address { get; set; }
        public int IsDelete { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string UserName { get; set; }
        public int Status { get; set; }
        public string AuditUser { get; set; }
        public System.DateTime AuditeTime { get; set; }
        public string Reason { get; set; }
        public string EquipmentNum { get; set; }
        public string EquipmentCode { get; set; }
        public int OutType { get; set; }
        public string ContractOrder { get; set; }
        public string Remark { get; set; }
    }
}
