//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProShatter
    {
        public int ID { get; set; }
        public string OrderNum { get; set; }
        public string UserName { get; set; }
        public string Reason { get; set; }
        public int IsDelete { get; set; }
        public System.DateTime CreateTime { get; set; }
        public string AuditUser { get; set; }
        public System.DateTime AuditTime { get; set; }
        public int Status { get; set; }
        public int IsMoveLoca { get; set; }
        public string MoveLocaNum { get; set; }
        public string Remark { get; set; }
    }
}
