
//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------


namespace entity
{

using System;
    using System.Collections.Generic;
    
public partial class PubDgvSet
{

    public string RegCode { get; set; }

    public string RegApp { get; set; }

    public string FormName { get; set; }

    public string ColumnName { get; set; }

    public int ColumnWidth { get; set; }

    public string DgvName { get; set; }

}

}
