//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        public int ID { get; set; }
        public string SupNum { get; set; }
        public string SupName { get; set; }
        public string Company { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string ContactName { get; set; }
        public string PCode { get; set; }
        public string CCode { get; set; }
        public string Address { get; set; }
        public string BankName { get; set; }
        public string BankCard { get; set; }
        public string Description { get; set; }
        public int IsDelete { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
