//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysResource
    {
        public int ID { get; set; }
        public string ResName { get; set; }
        public int ParentID { get; set; }
        public int Sort { get; set; }
        public int IsDelete { get; set; }
        public string Url { get; set; }
        public string CssName { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int Depart { get; set; }
        public int ResType { get; set; }
        public string Remark { get; set; }
    }
}
