//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Plan
    {
        public int ID { get; set; }
        public string PlanNum { get; set; }
        public string ConOrderNum { get; set; }
        public Nullable<int> ConId { get; set; }
        public Nullable<int> DetailId { get; set; }
        public int IndexNum { get; set; }
        public System.DateTime PlanDate { get; set; }
        public Nullable<System.DateTime> PlanStart { get; set; }
        public Nullable<System.DateTime> PlanEnd { get; set; }
        public Nullable<int> Status { get; set; }
        public System.DateTime CreateTime { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public string CreateUser { get; set; }
        public string Remark { get; set; }
        public int IsDelete { get; set; }
        public Nullable<int> Rate { get; set; }
        public Nullable<int> IsSticker { get; set; }
        public Nullable<int> IsPsAudite { get; set; }
        public Nullable<int> PsAudite { get; set; }
        public Nullable<System.DateTime> PSStart { get; set; }
        public Nullable<System.DateTime> PSEnd { get; set; }
        public Nullable<int> IsCutMat { get; set; }
        public Nullable<System.DateTime> CutMatStart { get; set; }
        public Nullable<System.DateTime> CusMatEnd { get; set; }
        public Nullable<int> CusMatStatus { get; set; }
        public Nullable<int> IsPrinter1 { get; set; }
        public Nullable<System.DateTime> Printer1Start { get; set; }
        public Nullable<System.DateTime> Printer1End { get; set; }
        public Nullable<int> Printer1IsPause { get; set; }
        public string Printer1Reason { get; set; }
        public Nullable<int> Printer1RealNum { get; set; }
        public Nullable<int> Printer1Status { get; set; }
        public Nullable<int> IsPrinter2 { get; set; }
        public Nullable<System.DateTime> Printer2Start { get; set; }
        public Nullable<System.DateTime> Printer2End { get; set; }
        public Nullable<int> Printer2IsPause { get; set; }
        public string Printer2Reason { get; set; }
        public Nullable<int> Printer2RealNum { get; set; }
        public Nullable<int> Printer2Status { get; set; }
        public Nullable<int> IsQC { get; set; }
        public Nullable<int> QCStatus { get; set; }
        public Nullable<int> QCAudite { get; set; }
        public string DensityValue { get; set; }
        public Nullable<System.DateTime> QCStart { get; set; }
        public Nullable<System.DateTime> QCEnd { get; set; }
        public Nullable<int> IsCutProduct { get; set; }
        public Nullable<int> CusProtatus { get; set; }
        public Nullable<System.DateTime> CusProStart { get; set; }
        public Nullable<System.DateTime> CusProEnd { get; set; }
        public Nullable<int> IsMQ { get; set; }
        public Nullable<int> MQStatus { get; set; }
        public Nullable<System.DateTime> MQStart { get; set; }
        public Nullable<System.DateTime> MQEnd { get; set; }
    }
}
