//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace entityTmp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CainzCustomer
    {
        public int ID { get; set; }
        public string FactoryNo { get; set; }
        public string FactoryName { get; set; }
        public string Phone { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
        public string Trader { get; set; }
        public string SendAddress { get; set; }
        public string Receiver { get; set; }
        public string Telephone { get; set; }
        public string Remark { get; set; }
        public string FirstNum { get; set; }
        public string TraderNo { get; set; }
        public string FactoryNameJP { get; set; }
    }
}
