//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace entityTmp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CainzProduct
    {
        public int ID { get; set; }
        public string Barcode { get; set; }
        public string FactoryID { get; set; }
        public string FactoryName { get; set; }
        public string Material { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public Nullable<decimal> Price { get; set; }
        public System.DateTime CreateTime { get; set; }
        public int Deleted { get; set; }
        public Nullable<System.DateTime> ModifyTime { get; set; }
        public Nullable<int> Modified { get; set; }
        public string TraderName { get; set; }
        public string TraderID { get; set; }
    }
}
